### ISSUE TITLE
GUI textures

### ISSUE THREAD

**Issue by Unimatrix36** [4nner/IronChests#10]
I have my own resource pack and I have added my own textures for this mod so it fits with my own pack.
But I can't add my own textures for the GUI. You know, when you open the chests.
When I open the JAR file and go to the textures folder there is no gui folder.
Just block, item and model

**Comment by 4nner** [comment]
The GUI is managed by LibGUI. This avoid the need for a texture for the GUI. I am not sure how to fulfill your need in this case. My suggestion would be to check LibGUI wiki/documentation.

**Comment by Unimatrix36** [comment]
Thanks for the answer.
I guess I need to find an similar mod that do use textures for the GUI.

**Comment by setzke** [comment]
For anyone finding this later:
Without declared textures, the mod uses LibGui's container defaults for everything. By making a resource pack overwriting those, we can change all the containers at once (they will have to be the same as each other).

Go to your mods, you'll need to unzip the iron chests jar, and the libGUI jar within it. Copy the `assets\libgui\textures\widget` folder (with that path) to a resource pack and edit the textures within. For me, the folder is here:
`minecraft\mods\IronChests-2.0.2\META-INF\jars\LibGui-8.1.1+1.20.1\assets\libgui\textures\widget`
The changes you'll see below are from two textures, one handling the corners+background, and the other for slots. (Small square in item_slot for chest inventory)

<img width="630" height="467" alt="Image" src="https://github.com/user-attachments/assets/a7f9a6c1-d9fa-4d5c-9c23-3d67996e7b8e" />


Before/After:
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/f045a7a2-63fa-4f72-b9e4-e26461d6c98a" />
<img width="1920" height="1200" alt="Image" src="https://github.com/user-attachments/assets/920ba306-a804-43a2-810d-0740d28c978d" />

**Comment by Wuffles1** [comment]
Any idea how to do this with 1.21.11? I couldn't figure it out with assets from [Default Dark Mode](https://modrinth.com/resourcepack/default-dark-mode) & [Default Dark Mode: Expansion](https://modrinth.com/resourcepack/default-dark-mode-expansion) resource packs.

**Comment by setzke** [comment]
Without spinning up an instance and messing with textures myself, I'd start here:

<img width="1458" height="728" alt="Image" src="https://github.com/user-attachments/assets/d691e3ea-b4c6-4e2e-8e56-e4072ac06112" />

<img width="1084" height="424" alt="Image" src="https://github.com/user-attachments/assets/1d18595f-f4ec-4701-bb30-dcf3d9f332e9" />

You'll want a resource pack with the path `assets\libgui\textures\widget\item_slot.png` and the two highlighted in `assets\libgui\textures\gui\sprites\widget`. I am confident the item slot's small icon is for chest item slots (larger box for bigger slots like in furnaces, etc.) I suspect the panel_light and panel_dark are the borders+internal background color of the chest GUI. After that, if anything is still unaltered, shouldn't be the hardest to figure out.

**Comment by Wuffles1** [comment]
Unfortunately I couldn't get this to work even with your instructions. I copy/pasted item_slot.png, panel_dark.png & panel_light.png assets from Default Dark Mode into their respective file locations and while the chest inventory panel border changed color correctly the background inventory slot color stayed vanilla for some reason. 

[DDM for Iron Chests v1.zip](https://github.com/user-attachments/files/26491477/DDM.for.Iron.Chests.v1.zip)

![Image](https://github.com/user-attachments/assets/065e4054-9520-4e2f-bf84-f8c91348ecd8)

Thank you for taking the time to try to help me regardless though I appreciate it.

Edit: While I couldn't figure it out for 1.21.11 I did finally get it working for my cobblemon install on 1.21.1.  :)
