### ISSUE TITLE
Doesn't work with FastChest

### ISSUE THREAD

**Issue by globalista-dev** [4nner/IronChests#14]
Chests can't be rendered as static blocks, which is what [FastChest](https://www.curseforge.com/minecraft/mc-mods/fastchest) does. It looks like Minecraft tries to render the chest both as a dynamic models and as a static one. I'm not sure which mod is responsible. 

![2022-02-14_18 32 20_2](https://user-images.githubusercontent.com/35036442/153949990-085a7900-1cc3-4e58-a5dd-0e8029dcc7dd.png)

![2022-02-14_18 28 07](https://user-images.githubusercontent.com/35036442/153949727-c7002c69-474f-4bc4-8a7e-6691a394af2e.png)
.

**Comment by 4nner** [comment]
Can you confirm that the following bug does not happen without FastChest?
Also could you please provide more information such as:
-Minecraft Version:
-Iron Chests Version:

Thanks

**Comment by globalista-dev** [comment]
It does not occur without FastChest. I can disable the mod in-game (it adds that feature) and the issue disappears. 

Minecraft version: 1.18.1
Iron Chests version: both 1.5.3 and 1.5.4 seem to be affected, but I did not test older versions.
