### ISSUE TITLE
Emerald To Crystal Chest Upgrade Recipe Overwrites Vanilla Green Stained Glass Recipe

### ISSUE THREAD

**Issue by Xenation** [4nner/IronChests#16]
The current crafting recipe for the "**Emerald Chest to Obsidian Upgrade**" (`ironchests:emerald_crystal_upgrade`) is the same as the vanilla recipe for "**Green Stained Glass**" (`minecraft:green_stained_glass`).
Because of this, the mod makes it impossible to craft green stained glass.
(Maybe the Green Dye could be replaced by Green Wool for example)

**Comment by 4nner** [comment]
Hello @Xenation , thank you for your bug report.
I will release an update for both 1.18.1 & 1.18.2 with an alternative crafting recipe for the upgrade.

**Comment by pappnase22** [comment]
can you pls uploud the 1.18.1 version of 1.5.6 ?

**Comment by 4nner** [comment]
All modpacks are migrating to 1.18.2, but If I have time I will release another build for 1.18.1
