### ISSUE TITLE
List of upgrades

### ISSUE THREAD

**Issue by Soggyshorts** [4nner/IronChests#24]
Assuming each "upgrade" increases capacity, would it be possible to add a chart of what each upgrade level changes to the description?
Also, is that configurable?
Thanks!

**Comment by 4nner** [comment]
Upgrade sizes are not configurable.
However, I could technically add an item description such as "Size increases: 27 -> 54".
I will consider adding this in the next update.

**Comment by Soggyshorts** [comment]
Ah sorry, I was unclear I just meant that I'd like to see the upgrade changes on the Curseforge Mod description page.
Something like
Iron 27
Gold 54
Emerald 81
etc

Thanks for the quick response though, cheers!

**Comment by 4nner** [comment]
I see. This can be done as well!
I might still introduce the tooltip on the items so that people can understand that in-game.

**Comment by 4nner** [comment]
The size list has been added on Curseforge!
