### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by Flaffi358** [4nner/IronChests#29]
Hello!

I made a translation for russian language. It would be nice if you integrate this to the mod
Thank you and good luck!

[Russian Translation.zip](https://github.com/4nner/IronChests/files/9420872/Russian.Translation.zip)

**Comment by Flaffi358** [comment]
First file isn't wrong. Can't edit it in some reason
That's the final version

[Russian translation v2.zip](https://github.com/4nner/IronChests/files/9420928/Russian.translation.v2.zip)

**Comment by 4nner** [comment]
Hello, thank you for your contribution. Could you please fork the project and then submit a pull request?
I will make sure to merge it and include it in the next release

**Comment by 4nner** [comment]
Closing as this issue is now stale.
