### ISSUE TITLE
Update to MC 1.19.2

### ISSUE THREAD

**Issue by DOD8495Gym** [4nner/IronChests#30]
I have a modpack that requires MC 1.19.2. Are you willing to provide "lip service" by merely stating that the version will support 1.19.2, or even just 1.19.x, even though no actual change was made?

**Comment by 4nner** [comment]
I should actually just update the dependencies and recompile the jar.
I will release the update today

**Comment by 4nner** [comment]
I've released the new version both on Curseforge and Modrinth
