### ISSUE TITLE
Chests not showing up in crafting grid output box.

### ISSUE THREAD

**Issue by Mystia98** [4nner/IronChests#31]
When I put the required ingredients to make a new chest, like the copper chest, nothing appears in the crafted output box.

Using newest version of the mod. 1.7.7  Fabric version.

**Comment by 4nner** [comment]
Are you playing on a server or single player?

**Comment by Mystia98** [comment]
Single player.

**Comment by 4nner** [comment]
I have just attempted to craft a Copper Chest, and I didn't find any issue. 

Could you specify which chest you are trying to craft, and what recipe you are using to attempt to craft it?

**Comment by Mystia98** [comment]
I was trying to make a copper chest, with 8 copper ingots and 1 chest. Chest in the middle with the ingots surrounding the chest.

**Comment by 4nner** [comment]
Can you see the mod items in the creative tab?

**Comment by Mystia98** [comment]
Yes, the mod items are in creative, I can spawn the chest in Creative, and also shows up in REI in survival.

**Comment by 4nner** [comment]
I am having trouble when trying to replicate the issue. As you can see, using version 1.7.7 I can craft a chest without any problem.
![Screenshot_1](https://user-images.githubusercontent.com/3206935/197491287-0b2e15bd-eca9-4d00-b91c-c7e83665bf84.png)

Are you playing a specific modpack? Is the copper the vanilla one, or a mod variant? Is the chest the vanilla one (trap chest not included) or a mod variant? Is there any mod that might have the same recipe, and therefor is conflicting with the copper chest recipe?

Could you please attach the log, starting from the game launch, to loading a world? That would help understand if the game is failing to register the recipe. Although if the recipe shows up in REI, it should have been registered successfully.

**Comment by 4nner** [comment]
Closing the issue as the user has not replied.
Feel free to reopen the issue in future if needed.
