### ISSUE TITLE
Texturepacks of original iron chest mod incompatible

### ISSUE THREAD

**Issue by jonalange** [4nner/IronChests#32]
I downloaded a texture pack for the original iron chest mod https://www.curseforge.com/minecraft/mc-mods/iron-chests
and thought it would work. Unfortunately it didn't out of the box. 

I compared the structure and noticed that the folder structure of the original iron chest mod is:
```
assets
   ironchest
```
but your's is:
```
assets
   ironchests
``` 
which makes any texturepack for the old mod not compatible out of the box with this mod.
I just renamed the texturepack folder, so it's not that big of an issue. Just would be nice working out of the box.

**Comment by 4nner** [comment]
I will perform the refactor when I will release an update for Minecraft 1.20
Changing the naming scheme is a breaking change, and would mean that anyone updating to a new version with the name changed from ironchests to ironchest would see their chests disappear.
