### ISSUE TITLE
[enhancement] Emerald crystal chest texture

### ISSUE THREAD

**Issue by SebastianDevus** [4nner/IronChests#33]
Since we already have the emerald chest be a reskin of the diamond chest, i think having a single, light blue crystal chest, looks very weird. A simple green crystal chest upgraded from emerald would be nice

**Comment by 4nner** [comment]
This can be surely implemented. Along with another crystal chest for Amethyst.
However, I have no time at the moment so I can't provide an ETA

**Comment by 4nner** [comment]
The emerald chest texture has been improved since the release for MC 1.18.x
