### ISSUE TITLE
[Bug] Mod compatibility issue

### ISSUE THREAD

**Issue by samolego** [4nner/IronChests#38]
Hello there!

I'm developer of ClientStorage mod (https://github.com/samolego/ClientStorage). Mods crash if interacted with each other, since the container size of the custom chests returned (`Container#getContainerSize`) is over 12, but when trying to set items using `Container#setItem` crashes it on slots higher than 12. (`#getItem` prob as well)

Could you update / override vanilla container methods to reflect storage capacities of custom chests?

**Comment by 4nner** [comment]
At the moment I do not have time to work on the mod I'm afraid. Anything other than small dependencies updates will have to wait quite a few months.

However, if anyone wants to submit a pull request with the change you need, I'll find the time to test, merge and publish the update.

**Comment by 4nner** [comment]
Fixed in #82
