### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by vico93** [4nner/IronChests#40]
Sorry to be that guy, but is there any plans to update this mod to 1.19.4?

**Comment by globalista-dev** [comment]
I've submitted a pull request that makes the mod compatible with Minecraft 1.19.4

Feel free to compile the mod from my fork (use the 1.19.4 branch)

**Comment by vico93** [comment]
@globalista-dev How can i compile this (using command line on Windows)?

**Comment by globalista-dev** [comment]
You should use an IDE for that. I'll compile the source code and post it under releases. That should be quite easier.

**Comment by vico93** [comment]
> You should use an IDE for that. I'll compile the source code and post it under releases. That should be quite easier.

Thanks a lot!

**Comment by globalista-dev** [comment]
It's here: https://github.com/globalista-dev/IronChests/releases/tag/1.7.9

Please do note that I haven't extensively tested this, but I didn't find any problems with the mod. If you find any, report them on my fork, not here.

**Comment by vico93** [comment]
> It's here: https://github.com/globalista-dev/IronChests/releases/tag/1.7.9
> 
> Please do note that I haven't extensively tested this, but I didn't find any problems with the mod. If you find any, report them on my fork, not here.

Roger that! Thank you so much!

**Comment by 4nner** [comment]
@vico93 @globalista-dev I will be merging the PR and releasing the mod on curseforge by the end of the day.
