### ISSUE TITLE
fix: lag

### ISSUE THREAD

**Issue by Flandre01** [4nner/IronChests#48]
I get 20/25fps when I open a chest. Even when it's empty the lag is huge

**Comment by 4nner** [comment]
Hi @Flandre01 could you please give more information about how many FPS are you expecting on average, and what PC components are you using?
The chest GUI is dynamically generated and might be though on old hardware. I've personally tested it and I did not notice anything more than a maximum 30% less FPS while the chest is open.

**Comment by Flandre01** [comment]
@4nner My pc is pretty bad but I still think it's weird. gpu: gtx 550ti, i53570k, 16gbram 1866hz average fps arround 180/200. I'm using it on fabric/sodium/iris
Sorry for my bad english, im Brazilian

**Comment by Flandre01** [comment]
> Hi @Flandre01 could you please give more information about how many FPS are you expecting on average, and what PC components are you using? The chest GUI is dynamically generated and might be though on old hardware. I've personally tested it and I did not notice anything more than a maximum 30% less FPS while the chest is open.
@4nner My pc is pretty bad but I still think it's weird. gpu: gtx 550ti, i53570k, 16gbram 1866hz average fps arround 180/200. I'm using it on fabric/sodium/iris (no shaders)
Sorry for my bad english, im Brazilian

**Comment by Yokoo2** [comment]
Hey, Im also having this issue. From where I average to about 230fps with 20 Render Distance I go down to 50fps when having a diamond chest opened. I tried tweaking some settings but to no avail. Is there maybe a discord server or something similar where you are more available?

**Comment by 4nner** [comment]
Tested in version 2.0.3 and appears to be fixed.
