### ISSUE TITLE
[BUG] Issue with missing chests on world upgrade

### ISSUE THREAD

**Issue by vojthus** [4nner/IronChests#53]
Scenario: upgrading the world from version 1.19.2 to 1.20.1.
The mod is updated as well (details below).
After applying fixes and opening the save after version upgrade all chest from the mod are missing.
 

Initial game version: 1.19.2 (Fabric 0.14.22)
Initial mod version: IronChests-1.7.7

Upgraded game version: 1.20.1 (Fabric 0.14.22)
Upgraded mod version: IronChests-2.0.0

**Comment by 4nner** [comment]
There was a warning to warn users against upgrading from 1.19.x to 1.20.x as this would have caused all the chests to disappear due to a name change. This is not a bug but rather a documented breaking change.
