### ISSUE TITLE
Crash on 1.20.1 server.

### ISSUE THREAD

**Issue by kotisoff** [4nner/IronChests#61]
[crash-2023-12-09_18.11.51-server.txt](https://github.com/4nner/IronChests/files/13624526/crash-2023-12-09_18.11.51-server.txt)

**Comment by kotisoff** [comment]
Mod version 2.0.0
Tried to install libgui, still crash

**Comment by KNIZE1007** [comment]
I have exactly the same issue. Any solutions?

**Comment by 4nner** [comment]
Fixed in #614630.
