### ISSUE TITLE
1.20.1 - Crashes when used on a server

### ISSUE THREAD

**Issue by KNIZE1007** [4nner/IronChests#62]
[crash_log.txt](https://github.com/4nner/IronChests/files/13727684/crash_log.txt)
crashes when any of the chests are opened on a server. it works fine in singleplayer, even when on a LAN world.

**Comment by Yoshun** [comment]
Hi,
Same here. My crash-report : https://pastebin.com/9SCTuFnD
Thanks :)

**Comment by aclef** [comment]
Same issue, looks like used UI library (https://github.com/CottonMC/LibGui/) version mismatch (`java.lang.NoSuchFieldError: backgroundPainter`)
[crash-2024-01-03_19.38.59-server.txt](https://github.com/4nner/IronChests/files/13822800/crash-2024-01-03_19.38.59-server.txt)

**Comment by Frog-Lover-Antony** [comment]
+1.
`java.lang.NoSuchFieldError: backgroundPainter`
[crash-2024-01-07_22.14.38-server.txt](https://github.com/4nner/IronChests/files/13855123/crash-2024-01-07_22.14.38-server.txt)

**Comment by bloodsbro** [comment]
Same issue
[crash-2024-01-11_16.22.13-server.txt](https://github.com/4nner/IronChests/files/13903825/crash-2024-01-11_16.22.13-server.txt)

**Comment by oldjollysanta** [comment]
The error points to the "LibGui" within the ironchest jar causing the error.
I downloaded the updated LibGui jar from:
https://github.com/CottonMC/LibGui/releases/tag/8.1.1
Opened **Ironchests-2.0.0.jar** using **Winrar**, Navigated to **META-INF\jars**
Added the new **LibGui-8.1.1+1.20.1.jar** file
Deleted the old **LibGui-8.0.0.jar** that was there
Then edited fabric.mod.json (in the main directory) and changed  **"file": "META-INF/jars/LibGui-8.0.0.jar"**
to:  **"file": "META-INF/jars/LibGui-8.1.1+1.20.1.jar"**

Tested and now works correctly on server without crashes.
Hope this helps!

**Comment by Absotively** [comment]
I have the same crash on 1.19.2. Using oldjollysanta's method to upgrade LibGui from 6.2.0 to 6.4.0 (the latest version with 1.19.2 support) did not help.

**Comment by 4nner** [comment]
Fixed in [1053ec9](https://github.com/4nner/IronChests/commit/1053ec940830eab9a85457aeb7ab902e6267b734).
