### ISSUE TITLE
Can't upgrade any chests

### ISSUE THREAD

**Issue by The-OmegaMale** [4nner/IronChests#8]
I shift + right click with the correct upgrade on my chests and nothing happens. This happens every single time. I do have OptiFabric and I'm playing in 1.18, but I have no idea what causes it. It could just be a mod that it's incompatible with but idk.

**Comment by 4nner** [comment]
Can you confirm that that the problem occurs when you try upgrading an Iron Chest to a Gold Chest or something else?
Upgrading from Wooden Chest to other is not supported at the moment.

**Comment by 4nner** [comment]
I have just tried quickly to upgrade a copper chest to an iron chest and by shifting + right clicking the upgrade worked as it should.
I tried on Minecraft 1.18.1

**Comment by foodtooth** [comment]
The wooden chest upgrade now shows WIP, hope it would come back soon 😆

**Comment by 4nner** [comment]
Closing this issue, as there is already an opened one #5
