### ISSUE TITLE
World upgrade 1.17 to 1.18 does not work Ironchests 1.5.3

### ISSUE THREAD

**Issue by alpha1bit** [4nner/IronChests#9]
Iron chests within 1.17 world works fine.  However when loading same world in 1.18 or 1.18.1 the existing chests do not appear in world and drop all containing items.  Placing new chests within 1.18 or 1.18.1 world works fine.  Upgrade does not work.  
Using Iron Chests 1.5.3, Optifine 1.8.1_HD_U_H4, Optifabric 1.12.9, Fabric Api 0.44+1.18, Minecraft 1.18.0 and 1.18.1

**Comment by 4nner** [comment]
Upgrade of worlds from 1.17.x to 1.18.x is unsupported by many mods, due to the way Mojang changed the way entities are managed.
